apiVersion: v1
kind: Secret
metadata:
    name: vsphere-csi-controller
    namespace: shared-services
stringData:
    data: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: vsphere-csi-controller
          namespace: kube-system
type: addons.cluster.x-k8s.io/resource-set
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-22T19:50:32Z"
    mac: ENC[AES256_GCM,data:5nt70YqDGr1apKn9IUNSBOhef4XAWYCt8orSE6z35LXN+947IZ+ZL7E+0c9jaSUf6nxZJ5ueMlwZ7yX/OA9HEA633IHg4LboN6nLaeqkCEf8D27+0j9L3G5ZfmGIrpT1Nv1QxE0jgUry/kC19NhJUp9kGUZadmL6ilPgDVAzG+Q=,iv:axif1+DgvtzQbDc10ww+JAcJ4lBT/fo3QFALLoh0Yi8=,tag:17SlxvKHj41fHYTsxQnMsA==,type:str]
    pgp:
        - created_at: "2022-12-22T19:50:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9VhhrDDnyi5AQ//cN6zIIbV3vsz60h2uutwaPTzCDV6WM0+epEYlnyyv4Jb
            uKwfAfxLDa0H1/KOMlZZNeplrwSRzkm0NThnsWonj8ap02R6RAS+iKmtETOuGiei
            gj5wfoV68/YfkvOcG8Quekk4wf4DWCQsefrBJq6PFMYO46dQpDhR15w6pnWjOuzz
            evo90+FXaAjE/E8tFgqK9BGpVAin71gggha7OoEtqJvLRPtz1H1wpGbX+sLsQalE
            NiEMbKSf5ZsYazc4HyMbP0Yjddj4R2HuoyKiHE1aRupCGarv8oyJ5+63pvp8CHWP
            XhT0ya5IsXiYUUz5CYe1eISN2xawxiJclNRAatJsH05hIlsjCav8i1fiiojHxVrM
            RYU9gdskBse8IUARh3ZTOvzvpMCtyMI+dbTCmhR8Qz7xQVwkuNLp2lWI63JXAVaC
            /y3oX6NHj34pc/NIRf/UwfXcnUzGSEYKsuCWvhAkodVWgPTrRSVkKOglJpnRtQdl
            ZaIQojWkP4CbQt9YZAAY1S6pQ5sxeG7zi0RKzMSWoDiq+bLZDuFXN3dAd7wJevbb
            YtyBFv8DnoVMPB3/OnTHzY/GacIm1Db1VLwfuuta2P7f6cNAaAKI06IuAIKpgZ6g
            4qOOgCpt0xO8CAQvUP3/jQRDjnXIOiTgJkR1IB5e/AtXTfVuRScAMUBtICu7fhfS
            XAF0Ei0YDRZMkF8zLJgFvcJ5PBplx7+jixpv/Pg/HdsLTQHUwUqZZ5w7X40Ihmw0
            iFUv9ahy+raiSueiRv58/5FGARjfZbhG9Qzbt0MNzVwfdpdo7AgAGHn8AXz4
            =+PZ8
            -----END PGP MESSAGE-----
          fp: FAC1CF820538F4A07C8F4657DAD5DC6A21303194
    encrypted_regex: ^(password|api-key|default_password)$
    version: 3.7.3
